name: MeshViewer Build Matrix

on: [push]

env:
  QT_VERSION: 6.0.0
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        # - {
        #     name: "Windows Latest x64", artifact: "Windows-x64.zip",
        #     os: windows-latest,
        #     environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
        #   }
        # - {
        #     name: "Windows Latest x86", artifact: "Windows-x86.zip",
        #     os: windows-latest,
        #     environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars32.bat"
        #   }
        - {
            name: "Linux Latest x64", artifact: "Linux-x64.zip",
            os: ubuntu-20.04
          }
        - {
            name: "macOS Latest x64", artifact: "macOS-x64.zip",
            os: macos-latest
          }
    steps:
    - uses: actions/checkout@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.0.0'
        modules: 'qtquick3d qtquicktimeline qtshadertools'

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
