name: MeshViewer Build Matrix

on: [push]

env:
  QT_VERSION: 6.0.0
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Windows Latest x64", artifact: "Windows-x64.zip",
            os: windows-latest,
            arch: x64
          }
        - {
            name: "Linux Latest x64", artifact: "Linux-x64.zip",
            os: ubuntu-20.04
          }
        - {
            name: "macOS Latest x64", artifact: "macOS-x64.zip",
            os: macos-latest
          }
    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.0.0'
        modules: 'qtquick3d qtquicktimeline qtshadertools'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Configure MSVC console
      if: matrix.config.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.2
        arch: ${{ matrix.arch }}


    - name: "Build"
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        cmake --build . --config $BUILD_TYPE


